config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events
  root 'homepage#index'
  as :user do
    get '/admin', to: 'devise/sessions#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show, :update, :edit, :destroy]
  
  def index
    @events = Event.all.order("created_at DESC").take(10)
  end 

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event # another HTTP request
    else
      render 'new' # does not send another HTTP request
    end
  end
  
  def new
    @event = Event.new
  end 
  
  def edit
  end
  
  def show
  end 
  
  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end 
  
  def destroy
    @event.destroy
    redirect_to events_path
  end 
  
  private
    def find_event
      @event = Event.find(params[:id])
    end
    
    def event_params
      params.require(:event).permit(:content, :start_date, :end_date,
                                    :place)
    end 
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/events/_form.html.haml
.container-fluid
  .container-form
    = simple_form_for @event do |f|
      .form-group.row
        .col-sm-2= f.label :content, "Text"
        .col-sm-10= f.input :content, label: false
      .form-group.row
        .col-sm-2= f.label :start_date, "Start date"
        .col-sm-10= f.input :start_date, as: :date, start_year: Date.today.year, 
                            end_year: Date.today.year + 1, 
                            order: [:day, :month, :year],
                            label: false
      .form-group.row
        .col-sm-2= f.label :end_date, "End date"
        .col-sm-10= f.input :end_date, as: :date, start_year: Date.today.year,
                            end_year: Date.today.year + 1,
                            order: [:day, :month, :year],
                            label: false
      .form-group.row
        .col-sm-2= f.label :place, "Place"
        .col-sm-10= f.input :place, label: false
      .form-group.row
        .col-sm-2
        .col-sm-10= f.button :submit, class: "create_event_button"

app/views/events/edit.html.haml
- if user_signed_in?
  %h1 Edit Event!
  
  = render 'form'
  
  = link_to "Cancel", event_path(@event)
- else
  %h2 Log in first to edit an event!

app/views/events/index.html.haml
%h1 Index

- @events.each do |event|
  %h2= link_to truncate(event.content, length:20), event
  %p= time_ago_in_words(event.created_at)
  %p= truncate(event.content, length:50)
  
- if user_signed_in?
  = link_to "Create Event", new_event_path

app/views/events/new.html.haml
- if user_signed_in?  
  .form-div
    %h1 New Event Creator
    = render 'form'
- else
  %h2 Log in first to edit an event!

app/views/events/show.html.haml
%h1 Congratulations!
Content: 
= @event.content
.di Start date: 
= @event.start_date
.di End date: 
= @event.end_date
.di Place: 
= @event.place
- if user_signed_in?
  .di
    = link_to "All Events", events_path
    = link_to "Edit Event", edit_event_path(@event)
    = link_to "Delete Event", event_path(@event), method: :delete, 
             data: { confirm: "Are you sure?" }

app/views/homepage/index.html.haml
.homepage-img-div= image_tag "homepage-unsplash.jpg", class: "homepage-img"

app/views/layouts/application.html.haml
%html
  %head
    - tag 'meta', {:content => "width=device-width, initial-scale=1.0, shrink-to-fit=no", :name => "viewport"}, true
    %title CompanyName | Event Management System
    = csrf_meta_tags
    = csp_meta_tag
    
    = stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css",
      integrity: "sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO",
      crossorigin: "anonymous"
    = stylesheet_link_tag    'application', media: 'all',
      'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "https://use.fontawesome.com/releases/v5.4.1/css/all.css",
      integrity: "sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz",
      crossorigin: "anonymous"
  
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark.sticky-top
      = link_to root_path do
        %i.fas.fa-chart-bar
        .navbar-brand CompanyName
      %button{:class => "navbar-toggler", :type => "button",
              :data-toggle => "collapse", :data-target => "#navbarSupportedContent",
              :aria-controls => "navbarSupportedContent", :aria-expanded => "false",
              :aria-label => "Toggle navigation"}
        %span.navbar-toggler-icon
      .collapse.navbar-collapse#navbarSupportedContent
        -# mr-auto -- items on the left, ml-auto -- items on the right
        %ul.navbar-nav.ml-auto
          %li.nav-item
            = link_to root_path do
              .nav-link About
          %li.nav-item
            = link_to new_user_session_path do
              .nav-link Sign in
          %li.nav-item
            = link_to new_event_path do
              .nav-link Create an Event
    - if flash[:notice]
      %p= flash[:notice]
    - if flash[:alert]
      %p= flash[:alert]
    = yield